In [1]:
import numpy as np, pandas as pd, _pickle as pkl

In [2]:
with open('./trains.pkl', 'rb') as f:
    trains = pkl.load(f)

In [86]:
df_subm = pd.read_csv('./input/submission.csv')

In [87]:
df_val = pd.read_csv('./input/val.csv')

In [92]:
its = []
for item in df_val.item_id:
    its.append("\"{},{},{}\"".format(item, item, item))

In [93]:
df_val3 = df_val

In [94]:
df_val3.item_id = its

In [95]:
df_val3.rename(columns={'item_id' : 'prediction'}, inplace=True)

In [96]:
df_val3.to_csv('./val3.csv', index=False)

In [49]:
test_lens = []
for u in df_subm.uid:
    test_lens.append(len(trains[u]))

In [61]:
sum(np.array(test_lens)<10)

442

In [47]:
trains[df_subm.loc[3, 'uid']]

[array([20180701211014865, '13988552323314653437881', 2002576010,
        '테슬라 CQR 남성 언더레이어 터틀넥 CQ-TUT102-TGN', 10710, '스포츠 의류', '기능성스포츠의류',
        '기능성의류 기타'], dtype=object),
 array([20180701210847437, '13988552323314653437881', 1979091461,
        '[무료배송]CQR 남성용 컴뱃집업 셔츠 CQ-TOS201(3색상 택1)', 19420, '스포츠 의류',
        '패딩/다운점퍼', '남성 패딩/다운점퍼'], dtype=object),
 array([20180701211507668, '13988552323314653437881', 1952066721,
        'CQR 택틱컬 팬츠 기능성 바지 작업복 근무복 카고바지', 15210, '등산/아웃도어', '남성등산복',
        '등산바지'], dtype=object),
 array([20180701204711119, '13988552323314653437881', 1977890779,
        '밀리터리 전술조끼/SDS Official US Military', 37720, '해외직구', '스포츠/레저',
        '스포츠남성패션'], dtype=object)]

In [6]:
ks = trains.keys()

In [11]:
df= pd.DataFrame(trains)

ValueError: arrays must all be same length

In [13]:
item

[array([20180725163443627, '15296467971395581275090', 2022841735,
        '에이플러스 스테이크소스260g A+/스테이크소스/돈가스', 2000, '가공식품', '소스', '소스 기타'],
       dtype=object),
 array([20180725163721337, '15296467971395581275090', 2117220028,
        '오쉐프 데미그라스 3kg 1개 데미글라소스 양식 소스', 10200, '가공식품', '소스', '소스 기타'],
       dtype=object),
 array([20180725163812153, '15296467971395581275090', 1078152755,
        '하인즈 데미그라스소스 290g 원터치', 2800, '가공식품', '조미료/양념', '조림/찌개소스'],
       dtype=object),
 array([20180725164012508, '15296467971395581275090', 2069878143,
        '[토리식품] 두레생협 돈가스소스(330g) 떡갈비소스 볶음밥소스 동그랑땡소스 돈가스소스 토마토돈가스', 14070,
        '가공식품', '소스', '돈까스소스'], dtype=object),
 array([20180725162037417, '15296467971395581275090', 2000917901,
        'CJ 이츠웰 스테이크소스 2k 소스 안심 함박 스테이', 14620, '가공식품', '소스', '스테이크소스'],
       dtype=object),
 array([20180725162736217, '15296467971395581275090', 2015122729,
        '[순수정육] 무항생제 유황오리 울금떡갈비1팩 200g 냉동', 5500, '축산', '축산가공식품', '소시지'],
       dtype=object),
 array([201807

In [15]:
lens = []
for key, item in trains.items():
#     print(key, item)
    lens.append(len(item))

In [16]:
len(lens)

230559

In [30]:
sum(np.array(lens)>500)

1281